name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
    version:
      description: 'Version of Auto to install (latest by default)'
      required: false

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Install Auto
        uses: ./
      - run: auto --version
